# Generated by Django 6.0 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Seller', 'Seller'), ('Viewer', 'Viewer')], max_length=10, null=True),
        ),
    ]
