# Generated by Django 6.0 on 2025-12-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
