# Generated by Django 6.0 on 2026-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('seller', 'Seller'), ('viewer', 'Viewer')], max_length=10, null=True),
        ),
    ]
