# Generated by Django 6.0 on 2025-12-29 17:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('decimal', 'Decimal')], max_length=20)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description for users')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rut', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'abstract': False,
                'indexes': [models.Index(fields=['rut'], name='inventory_c_rut_901517_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.company')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('decimal', 'Decimal')], max_length=20)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description for users')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='inventory.company')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='inventory.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Barcode for scanning', max_length=50)),
                ('price', models.DecimalField(decimal_places=0, help_text='Sales price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Cost price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_includes_tax', models.BooleanField(default=True, help_text='Price includes IVA (19%)')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Dynamic product attributes based on template')),
                ('minimum_stock', models.FloatField(default=0, help_text='Minimum stock level for alerts', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_of_measure', models.CharField(default='unit', help_text='Unit of measure (unit, kg, liter, etc.)', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('default_value', models.CharField(blank=True, help_text='Default value for this attribute', max_length=255)),
                ('custom_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_attributes', to='inventory.customattribute')),
                ('global_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_attributes', to='inventory.globalattribute')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_attributes', to='inventory.template')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('is_main', models.BooleanField(default=False, help_text='Main warehouse')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='inventory.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('resulting_balance', models.FloatField(help_text='Balance after this movement')),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('loss', 'Loss/Waste'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_document', models.CharField(blank=True, help_text='Reference number (invoice, purchase order, etc.)', max_length=100)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, help_text='Unit cost at the time of movement (for IN movements)', max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockrecord')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'name'], name='inventory_c_company_07f959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'company')},
        ),
        migrations.AddIndex(
            model_name='customattribute',
            index=models.Index(fields=['company', 'slug'], name='inventory_c_company_8468cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customattribute',
            unique_together={('slug', 'company')},
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['company', 'name'], name='inventory_t_company_f79d6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('name', 'company')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'sku'], name='inventory_p_company_85d371_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'category'], name='inventory_p_company_549574_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='templateattribute',
            index=models.Index(fields=['template', 'order'], name='inventory_t_templat_7cf3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_main'], name='inventory_w_company_0a7855_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'company')},
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_87a496_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['warehouse', 'current_quantity'], name='inventory_s_warehou_d95ad1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_record', '-created_at'], name='inventory_s_stock_r_0146fb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['account', '-created_at'], name='inventory_s_account_7f5361_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_document'], name='inventory_s_referen_7f43d8_idx'),
        ),
    ]
